In [12]:
import pandas as pd
import numpy as np

data = {
    "Name":['Aavash', 'Aryam', 'Noah', 'Bibek'],
    "Age":[20, 21, 29, 12],
    "City":['Imadol', 'Mangalbazar', 'Bhaktapur', 'Pimbahal'],
    "Salary":[20000, 21000, 29, np.nan],
}
df = pd.DataFrame(data)
df

Name  Age         City   Salary
0  Aavash   20       Imadol  20000.0
1   Aryam   21  Mangalbazar  21000.0
2    Noah   29    Bhaktapur     29.0
3   Bibek   12     Pimbahal      NaN

In [2]:
df.isnull().sum()

Name      0
Age       0
City      0
Salary    1
dtype: int64

In [5]:
df.notnull()

Name   Age  City  Salary
0  True  True  True    True
1  True  True  True    True
2  True  True  True    True
3  True  True  True   False

In [4]:
df.notnull().sum()

Name      4
Age       4
City      4
Salary    3
dtype: int64

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    4 non-null      object 
 1   Age     4 non-null      int64  
 2   City    4 non-null      object 
 3   Salary  3 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 260.0+ bytes


In [7]:
df.dropna()

Name  Age         City   Salary
0  Aavash   20       Imadol  20000.0
1   Aryam   21  Mangalbazar  21000.0
2    Noah   29    Bhaktapur     29.0

In [10]:
df.dropna(inplace=True)

In [13]:
df

Name  Age         City   Salary
0  Aavash   20       Imadol  20000.0
1   Aryam   21  Mangalbazar  21000.0
2    Noah   29    Bhaktapur     29.0
3   Bibek   12     Pimbahal      NaN

In [2]:
import pandas as pd
import numpy as np

data = {
    "Name":['Aavash', 'Aryam', 'Noah', 'Bibek','Aavash', 'Aryam', 'Noah', 'Bibek'],
    "Age":[20, 21, 29, 12,20, 21, 29, 12],
    "City":['Imadol', 'Mangalbazar', 'Bhaktapur', 'Pimbahal','Imadol', 'Mangalbazar', 'Bhaktapur', 'Pimbahal'],
    "Salary":[20000, 21000, 29, np.nan,20000, 21000, 29, 1000],
}
df = pd.DataFrame(data)
df

Name  Age         City   Salary
0  Aavash   20       Imadol  20000.0
1   Aryam   21  Mangalbazar  21000.0
2    Noah   29    Bhaktapur     29.0
3   Bibek   12     Pimbahal      NaN
4  Aavash   20       Imadol  20000.0
5   Aryam   21  Mangalbazar  21000.0
6    Noah   29    Bhaktapur     29.0
7   Bibek   12     Pimbahal   1000.0

In [20]:
df.drop_duplicates(inplace=True)
df

Name  Age         City   Salary
0  Aavash   20       Imadol  20000.0
1   Aryam   21  Mangalbazar  21000.0
2    Noah   29    Bhaktapur     29.0
3   Bibek   12     Pimbahal      NaN
7   Bibek   12     Pimbahal   1000.0

In [21]:
df.dropna(subset=['Salary'])

Name  Age         City   Salary
0  Aavash   20       Imadol  20000.0
1   Aryam   21  Mangalbazar  21000.0
2    Noah   29    Bhaktapur     29.0
7   Bibek   12     Pimbahal   1000.0

In [22]:
df

Name  Age         City   Salary
0  Aavash   20       Imadol  20000.0
1   Aryam   21  Mangalbazar  21000.0
2    Noah   29    Bhaktapur     29.0
3   Bibek   12     Pimbahal      NaN
7   Bibek   12     Pimbahal   1000.0

In [32]:
# boxplot
data = {
    "Name":['Aavash', 'Aryam', 'Noah', 'Bibek'],
    "Score":[100, 85, np.nan, 82.5],
    }
df = pd.DataFrame(data)
df

Name  Score
0  Aavash  100.0
1   Aryam   85.0
2    Noah    NaN
3   Bibek   82.5

In [33]:
Q1 = df['Score'].quantile(0.25)
Q3 = df['Score'].quantile(0.75)
IQR = Q3-Q1
print(Q1,Q3, IQR)

lower_bound = Q1 - 1.5 *IQR
upper_bound = Q1 + 1.5 *IQR

outliers = df[(df['Score']<lower_bound)| (df['Score']>upper_bound)]
outliers

83.75 92.5 8.75


Name  Score
0  Aavash  100.0

In [34]:
df.fillna(df['Score'].mean())

Name       Score
0  Aavash  100.000000
1   Aryam   85.000000
2    Noah   89.166667
3   Bibek   82.500000

In [40]:
df.fillna(df['Score'].median())

Name  Score
0  Aavash  100.0
1   Aryam   85.0
2    Noah   85.0
3   Bibek   82.5

In [33]:
data = {
    "name":['Aavash', 'Aryam', 'Noah', 'Bibek', 'Saroj', 'Bibek'],
    "age":[20, np.nan, 29, 12, np.nan, 12],
    "gender":['M', 'M', 'M', 'F', 'M', 'F'],
    "city":['Imadol', 'Mangalbazar', 'Bhaktapur', 'Pimbahal', 'Mangalbazar', 'Pimbahal'],
    "marks":[80, 100, np.nan, np.nan, 50, np.nan],
}
df = pd.DataFrame(data)
df

name   age gender         city  marks
0  Aavash  20.0      M       Imadol   80.0
1   Aryam   NaN      M  Mangalbazar  100.0
2    Noah  29.0      M    Bhaktapur    NaN
3   Bibek  12.0      F     Pimbahal    NaN
4   Saroj   NaN      M  Mangalbazar   50.0
5   Bibek  12.0      F     Pimbahal    NaN

In [19]:
df.isnull()

name    age  gender   city  marks
0  False  False   False  False  False
1  False   True   False  False  False
2  False  False   False  False   True
3  False  False   False  False   True
4  False   True   False  False  False
5  False  False   False  False   True

In [20]:
df.isnull().sum()

name      0
age       2
gender    0
city      0
marks     3
dtype: int64

In [21]:
df.dropna()

name   age gender    city  marks
0  Aavash  20.0      M  Imadol   80.0

In [22]:
df.fillna(20)

name   age gender         city  marks
0  Aavash  20.0      M       Imadol   80.0
1   Aryam  20.0      M  Mangalbazar  100.0
2    Noah  29.0      M    Bhaktapur   20.0
3   Bibek  12.0      F     Pimbahal   20.0
4   Saroj  20.0      M   Kumaripati   50.0
5   Bibek  12.0      F     Pimbahal   20.0

In [23]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5     True
dtype: bool

In [29]:
af = df.copy()

In [34]:
df.drop_duplicates(inplace=True)

In [35]:
df

name   age gender         city  marks
0  Aavash  20.0      M       Imadol   80.0
1   Aryam   NaN      M  Mangalbazar  100.0
2    Noah  29.0      M    Bhaktapur    NaN
3   Bibek  12.0      F     Pimbahal    NaN
4   Saroj   NaN      M  Mangalbazar   50.0

In [36]:
af

name   age gender         city  marks
0  Aavash  20.0      M       Imadol   80.0
1   Aryam   NaN      M  Mangalbazar  100.0
2    Noah  29.0      M    Bhaktapur    NaN
3   Bibek  12.0      F     Pimbahal    NaN
4   Saroj   NaN      M   Kumaripati   50.0
5   Bibek  12.0      F     Pimbahal    NaN

In [37]:
df.drop_duplicates(['city'])

name   age gender         city  marks
0  Aavash  20.0      M       Imadol   80.0
1   Aryam   NaN      M  Mangalbazar  100.0
2    Noah  29.0      M    Bhaktapur    NaN
3   Bibek  12.0      F     Pimbahal    NaN

In [39]:
df.dropna(subset=['age'])

name   age gender       city  marks
0  Aavash  20.0      M     Imadol   80.0
2    Noah  29.0      M  Bhaktapur    NaN
3   Bibek  12.0      F   Pimbahal    NaN

In [40]:
df

name   age gender         city  marks
0  Aavash  20.0      M       Imadol   80.0
1   Aryam   NaN      M  Mangalbazar  100.0
2    Noah  29.0      M    Bhaktapur    NaN
3   Bibek  12.0      F     Pimbahal    NaN
4   Saroj   NaN      M  Mangalbazar   50.0

In [42]:
import numpy as np
arr = np.array ([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [43]:
arr_2d = np.array ([[1,2,3],[4,5,6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [44]:
arr_3d = np.array ([[[1,2,3], [4,5,6], [7,8,9]]])
print(arr_3d)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [54]:
print(arr.ndim)
print(arr_2d.ndim)
print(arr_3d.ndim)

print(arr.shape)
print(arr_2d.shape)
print(arr_3d.shape)

print(arr.dtype)
print(arr_2d.dtype)
print(arr_3d.dtype)

1
2
3
(5,)
(2, 3)
(1, 3, 3)
int64
int64
int64


In [61]:
print(arr.mean())
print(arr_2d.mean())
print(arr_3d.mean())

3.0
3.5
5.0


In [62]:
print(np.median(arr))
print(np.median(arr_2d))
print(np.median(arr_3d))

3.0
3.5
5.0


In [63]:
print(np.sqrt(arr))
print(np.sqrt(arr_2d))
print(np.sqrt(arr_3d))

[1.         1.41421356 1.73205081 2.         2.23606798]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
[[[1.         1.41421356 1.73205081]
  [2.         2.23606798 2.44948974]
  [2.64575131 2.82842712 3.        ]]]
