In [1]:
import numpy as np
arr = np.array ([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [2]:
arr_2d = np.array ([[1,2,3],[4,5,6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [3]:
arr_3d = np.array ([[[1,2,3], [4,5,6], [7,8,9]]])
print(arr_3d)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [4]:
arr_3d.shape #matrix shape rows column and dimension)

(1, 3, 3)

In [5]:
arr_3d.ndim #dimension

3

In [6]:
arr = np.ones ((3,3)) #3 by 3 matrix is formed
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [7]:
arr = np.zeros ((3,3)) # 0 by 0 matrix is formed
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
arr = np.arange(10) # range from 0-9
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
arr = np.arange(2,10) #range from 2-9
print(arr)

[2 3 4 5 6 7 8 9]


In [10]:
arr = np.linspace(1,10) # how can range divide from 1 to 1o
print(arr)

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


In [11]:
arr = np.linspace(1,2,4)

In [12]:
arr

array([1.        , 1.33333333, 1.66666667, 2.        ])

In [13]:
arr_3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr_3d.shape)

(2, 2, 3)


In [14]:
arr_3d.reshape((2,6))

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [15]:
arr_3d.shape

(2, 2, 3)

In [16]:
arr = np.array([1,2.5,3,4])
arr.dtype # Data Type (default value)

dtype('float64')

In [17]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr.mean())
print(arr.max())
print(arr.sum())
print(arr.min())
print(arr.var())
print(arr.std())

5.5
10
55
1
8.25
2.8722813232690143


In [18]:
arr = np.array([1,2,3,4,5,6])
print(arr[0])
print(arr[-4]) #Indexing
print(arr[2:4]) #Slicing


1
3
[3 4]


In [19]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
print(arr_2d[2][0]) # 0,1,2 index rows column

7


In [21]:
arr = np.array([2,4,6,8,10])
np.where(arr>4,'Greater than 4', 'Less than 4') # Print text according to number (Filtering)

array(['Less than 4', 'Less than 4', 'Greater than 4', 'Greater than 4',
       'Greater than 4'], dtype='<U14')

In [22]:
import time  
import numpy as np

# Define two Python lists 
py_list1 = list(range(1000000)) 
py_list2 = list(range(1000000, 2000000))  

# Define two Numpy arrays 
array1 = np.arange(1000000) 
array2 = np.arange(1000000, 2000000)  

# Adding Python lists 
start_time = time.time() 
result_list = [a + b for a, b in zip(py_list1, py_list2)] 
print("Time taken to add Python lists: ", time.time() - start_time)  

# Adding Numpy arrays 
start_time = time.time() 
result_array = array1 + array2 
print("Time taken to add Numpy arrays: ", time.time() - start_time)

Time taken to add Python lists:  0.07294392585754395
Time taken to add Numpy arrays:  0.0041942596435546875
