In [1]:
import math

r = float(input("Enter the radius value "))
x = math.pi*r**2

print('The area of circle is', x)

The area of circle is 28.274333882308138


In [2]:
a = [1,2,3,4]

In [3]:
a[-1]

4

In [9]:
# MEAN
# x = sumof(x)/N

sum = 0
for num in a:
    sum = sum+num

In [10]:
print(sum)

10


In [12]:
mean= sum/len(a)
print(mean)

2.5


In [5]:
import numpy as np
arr = np.array([1,2,3])

print(arr)

[1 2 3]


In [8]:

arr_2d = np.array([[1,2,3], [4,5,6]])

print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [17]:

arr_3d = np.array([[[1,2,3], [4,5,6], [7,8,9], [3,6,9]]])

print(arr_3d)

[[[1 2 3]
  [4 5 6]
  [7 8 9]
  [3 6 9]]]


In [18]:
arr_3d.shape

(1, 4, 3)

In [19]:
arr_3d.ndim

3

In [20]:
arr = np.zeros((3,3))

In [21]:
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
arr = np.arange(2,10)
arr

array([2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
arr = np.arange(2,10,2)
arr

array([2, 4, 6, 8])

In [ ]:
arr = np.linspace(1,10,5)
arr


array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [47]:
ar = arr_3d.reshape((2,6))
ar.shape

(2, 6)

In [41]:
arr_3d.shape

(1, 4, 3)

In [42]:
arr_3d

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
        [3, 6, 9]]])

In [43]:
arr.dtype

dtype('float64')

In [50]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr.mean())
print(arr.max())
print(arr.min())
print(arr.sum())
print(arr.var())
print(arr.std())

5.0
9
1
45
6.666666666666667
2.581988897471611


In [57]:
arr_2d = np.array([[1,2,3], [4,5,6], [2,3,9]])

print(arr_2d)

[[1 2 3]
 [4 5 6]
 [2 3 9]]


In [62]:
print(arr_2d[2][2])

9


In [65]:
import numpy as np
arr_1d = np.array([1,2,3,4,5])
print(arr_1d[1:3])
print(arr_1d[:2])
print(arr_1d[1])

[2 3]
[1 2]
2


In [ ]:
# np.where

arr = np.array([1,2,3,4,5])
# np.where(arr>4, 'Greater than 4', 'Less than 4')
np.where(arr>4, 0, 1)

array([1, 1, 1, 1, 0])